### ISSUE TITLE
Question about reproduction of Figure 15 in the paper

### ISSUE THREAD

**Issue by skysky0208** [cmu-snap/SurgeProtector#2]
@NAtre 

Hello, nice to meet you.
I am a first-year master's student at Osaka University in Japan.

We are currently trying to reproduce the results of the SurgeProtector paper (Figure 15), but it is not working.

I will explain my situation in detail.
Environment: Ubuntu 20.04.5 LTS
Package: Python 3.8+, Boost  C++  20.11.3, Libconfig 1.7.3+

We were able to execute example_1.cfg and iid_job_sizes.cfg using the method described in the README.
The environment variables in the code were set appropriately
（$INSERT_CSV_TRACE_FILE_PATH_HERE  =  "/home/user/SurgeProtector/simulator/traces/full_matcher.csv" )

However, if we run the following using full_matcher.cfg, an error will occur.
```
sudo python3 generate_jobs.py 
"${SURGEPROTECTOR_ROOT_DIR}/build/bin/simulator"     "${SURGEPROTECTOR_ROOT_DIR}/simulator/configs/templates/full_matcher.cfg"     "${SURGEPROTECTOR_ROOT_DIR}/simulator/data/full_matcher"
--policies=fcfs,fq,sjf,wsjf     --innocent_rates=100M,500M,900M     --attack_rates=1M,3M,7M,10M,30M,70M,100M,300M,700M
```

<img width="725" alt="image" src="https://github.com/cmu-snap/SurgeProtector/assets/55139437/3d2694ef-efdd-450a-ae74-5a4b456bf1d2">

We suspect that the cause is that the following code in simulator/scruipts/generete_jobs.py does not generate the contents of log.packets.
<img width="606" alt="image" src="https://github.com/cmu-snap/SurgeProtector/assets/55139437/54e9a8ef-79e2-4c56-8993-c0558d2523e2">

Please let me know if there are any other changes that need to be made to reproduce Figure 15.

Best regards.

**Comment by NAtre** [comment]
Hello! Thank you for reaching out, and my apologies for the long turnaround. Yes, it's a quick fix: please change [this line](https://github.com/cmu-snap/SurgeProtector/blob/master/simulator/configs/templates/full_matcher.cfg#L15) in the full matching template configuration file to point to the trace (i.e., hardcode the path instead of setting an environment variable). For instance, on my machine, the updated configuration would look like this:

```
application =
{
    type = "echo";                      # Echoes job sizes in trace
    stsf = 1;
    max_attack_job_size_ns = 62670;     # Max attack job size in ns. The 63 us value corresponds
                                        # to the maximum time the Pigasus Full Matcher spends on
                                        # an *innocent* packet for the workloads we've evaluated;
                                        # a real attack should be able to do even better (making
                                        # both FCFS and FQ perform worse).
};

innocent_traffic =
{
    type = "trace";
    trace_fp = "/home/nirav/github/surge_protector/simulator/traces/full_matcher.csv";
};
```

Please let me know if you still run into any issues :)

Best Regards,
Nirav

**Comment by skysky0208** [comment]
Thank you for your reply.
I was able to successfully reproduce it using the method you taught me!

I appreciate your kindness.

Best Regards,
Natsumi Sakamoto
